### ISSUE TITLE
Big Game Bugs

### ISSUE THREAD

**Issue by lorenzfresh** [daniel-amthauer/BMeshUnreal#2]
you are lead developer at behaviour interactive? i applied to you and i want to help you to get rid of the cheaters but unfortunately you are too stupid to give me a change here is a project to change the range on your servers. https://github.com/lorenzfresh/DBD-RankChanger  

Please Fix This...

**Comment by daniel-amthauer** [comment]
@lorenzfresh if you had taken the time to read my profile correctly, you'd realize I'm not currently a lead developer at Behaviour Interactive. I've been at ACE Team since 2016, and never had any sort of involvement with Dead By Daylight.
I think your attitude is probably the reason Behaviour Interactive passed on your job application, so if you seriously want a job at a company like that I suggest you adjust it.

Pro tip: even if you take it back afterwards by editing your comment I still got the original text as an email notification, so keep that in mind before being so impulsive again.

**Comment by lorenzstarling** [comment]
Hello, I hope you're doing well. Its been a while... but came up and I wanted to sincerely apologize for my past behavior. My previous message was inappropriate, and I have learned from it

If you don't mind, I would like to request the deletion of this GitHub issue It would greatly help me put the past behind.

Again I apologize and thank you for your understanding.

Happy coding!

**Comment by daniel-amthauer** [comment]
Hi! This was a really unexpected message! I'm happy to hear you're doing well and happy to oblige. I'll delete the issue now 👍
